name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Pull latest code files
        uses: actions/checkout@v3
      - name: Install rust tooling
        uses: actions-rs/toolchain@v1.0.6
        with:
          components: clippy
      - name: Verify code compiles
        run: cargo build
      - name: Verify tests complete
        run: cargo test
      - name: Verify code style
        run: cargo clippy
